apiVersion: v1
kind: Secret
metadata:
  name: gitlab-auth
  annotations:
    tekton.dev/git-0: http://192.168.0.153:8090/
type: Opaque
stringData:
  .git-credentials: |
    http://root:Lw1994100713..@192.168.0.153:8090
  .gitconfig: |
    [user]
        name = root
        email = 1037231547@qq.com

    [core]
        editor = vim
        autocrlf = input

    [alias]
        co = checkout
        br = branch
        ci = commit
        st = status