apiVersion: v1
kind: Service
metadata:
  name: el-trigger-rd-pipeline-eventlistener-nodeport
  namespace: cicd
spec:
  type: NodePort
  ports:
  - name: http-listener
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30100  # 这里指定 NodePort 端口
  - name: http-metrics
    port: 9000
    protocol: TCP
    targetPort: 9000
    nodePort: 30300  # 这里指定 NodePort 端口
  selector:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: trigger-rd-pipeline-eventlistener



    kubectl patch svc tekton-dashboard -n tekton-pipelines -p '{"spec": {"type": "NodePort"}}'
