apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-data-pvc-1
  namespace: cicd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client  # 根据你的存储类进行调整
